version: '3'

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn run start:dev --debug 0.0.0.0:${APP_DEBUG_PORT}'
    ports:
      - '${APP_OUT_PORT}:${APP_PORT}'
      - '${APP_DEBUG_OUT_PORT}:${APP_DEBUG_PORT}'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
